name: Release obsidian plugin

on:
    workflow_dispatch:
        inputs:
            bump:
                default: false
                description: "Bump version based on semantic release"
                type: boolean
                required: false
            beta:
                default: false
                description: "Make a beta release"
                type: boolean
                required: false
    push:
        tags:
            - "*"
permissions:
    contents: write

jobs:
    echo:
        runs-on: ubuntu-latest
        outputs:
            STYLE: ${{ fromJson(steps.style.outputs.STYLE) }}
        steps:
            - name: echo
              run: |
                  echo EVENT NAME =  ${{ github.event_name }}
                  echo BETA = ${{ inputs.beta || false}}
                  echo BUMP = ${{ inputs.bump || false}}
            - name: Style exists
              id: style
              run: |
                  if [ -f "styles.css" ] || [ -f "src/styles.css" ]; then
                      echo "STYLE='true'" >> "$GITHUB_OUTPUT"
                  else
                      echo "STYLE='false'" >> "$GITHUB_OUTPUT"
                  fi
