name: Release obsidian plugin

on:
    workflow_dispatch:
        inputs:
            bump:
                default: false
                description: "Bump version based on semantic release"
                type: boolean
                required: false
            beta:
                default: false
                description: "Make a beta release"
                type: boolean
                required: false
    push:
        tags:
            - "*"
permissions:
    contents: write

jobs:
    echo:
        runs-on: ubuntu-latest
        outputs:
            STYLE: ${{ fromJson(steps.style.outputs.STYLE) }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: echo
              run: |
                  echo EVENT NAME =  ${{ github.event_name }}
                  echo BETA = ${{ inputs.beta || false}}
                  echo BUMP = ${{ inputs.bump || false}}
            - name: Style exists
              id: style
              run: |
                  echo "STYLE=false" >> "$GITHUB_OUTPUT"
                  if [[ -f "styles.css" || -f "src/styles.css" ]]; then
                    echo "STYLE=true" >> "$GITHUB_OUTPUT"
                  else
                    echo "STYLE=false" >> "$GITHUB_OUTPUT"
                  fi

    release:
        if: (github.event_name == 'push') || (github.event_name == 'workflow_dispatch' && !inputs.bump)
        uses: mara-li/reusable-workflows/.github/workflows/obsidian-plugin-release.yaml@main
        needs: echo

        with:
            PLUGIN_NAME: explorer-hidder
            CACHE: "pnpm"
        secrets:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    bump-version-and-release:
        if: ${{ inputs.bump }}
        needs: echo
        uses: mara-li/reusable-workflows/.github/workflows/obsidian-plugin-bump-version.yaml@main
        with:
            PLUGIN_NAME: explorer-hidder
            BETA: ${{ inputs.beta }}
            CACHE: "pnpm"
        secrets:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
