name: Test
on:
    workflow_dispatch:
jobs:
    test:
        env:
            CHANGELOG: ""
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: echo
              run: |
                  echo EVENT NAME =  ${{ github.event_name }}
            - name: setup node
              uses: actions/setup-node@v4
            - name: test changelog EOF
              run: |
                  npx rexreplace "^.*?#+\s\[.*?\n.*?(?=\s*#+\s\[)" "_" -s -M -G -m -o "CHANGELOG.md" > CHANGELOG-LATEST.md
                  cat CHANGELOG-LATEST.md >> $GITHUB_STEP_SUMMARY
                  CHANGELOG=$(cat CHANGELOG-LATEST.md)
                  echo "CHANGELOG<<EOF" >> $GITHUB_ENV
                  echo "$CHANGELOG" >> $GITHUB_ENV
                  echo "EOF" >> $GITHUB_ENV
            - name: test2
              run: |
                  echo "${{ env.CHANGELOG}}"
